services:
  postgres:
    image: postgres:latest
    container_name: clipnest-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: clipnest
      POSTGRES_PASSWORD: clipnest
      POSTGRES_DB: clipnest_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  mailpit:
    image: axllent/mailpit
    container_name: clipnest-mailpit
    restart: unless-stopped
    volumes: 
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  minio:
    image: 'quay.io/minio/minio:latest'
    container_name: clipnest-minio
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=clipnest
      - MINIO_ROOT_PASSWORD=clipnest
    volumes:
      - 'minio_data:/data'
    ports:
      - 9000:9000 # S3
      - 9001:9001 # UI

volumes:
  pgdata:
  minio_data:
